MagicVilla_Web/Controllers/VillaNumberController.cs
using AutoMapper;
using MagicVilla_Utility;
using MagicVilla_Web.Models;
using MagicVilla_Web.Models.DTO;
using MagicVilla_Web.Models.ViewModels;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace MagicVilla_Web.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IVillaNumberService _villaNumberService;
        private readonly IVillaService _villaService;

        public VillaNumberController(IMapper mapper, IVillaNumberService villaNumberService, IVillaService villaService)
        {
            this._mapper = mapper;
            this._villaNumberService = villaNumberService;
            this._villaService = villaService;
        }
        public async Task<IActionResult> IndexVillaNumber(int pageSize = 5, int pageNumber = 1, string searchString = "")
        {
            List<VillaNumberDTO> list = new List<VillaNumberDTO>();

            var response = await _villaNumberService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionTokenName), pageSize, pageNumber, searchString);
            var paginationHeaderValue = response.Headers.FirstOrDefault(x => x.Key == "X-Pagination").Value[0];

            var pagination = JsonConvert.DeserializeObject<Pagination>(paginationHeaderValue);

            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<VillaNumberDTO>>(Convert.ToString(response.Result));
            }

            var paginatedResults = new PaginatedListDTO(list, pagination.TotalResultsCount, pageNumber, pageSize, searchString);

            return await Task.Run(() => View(paginatedResults));
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateVillaNumber()
        {
            VillaNumberCreateVM villaNumberVM = new();
            var response = await _villaService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionTokenName));
            if (response != null && response.IsSuccess)
            {
                villaNumberVM.VillaList = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result)).Select(x => new SelectListItem()
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });
            }
            return await Task.Run(() => View(villaNumberVM));
        }

        [HttpPost]
        [Authorize(Roles = "admin")]

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateVillaNumber(VillaNumberCreateVM model)
        {

            if (ModelState.IsValid)
            {
                var response = await _villaNumberService.CreateAsync<APIResponse>(model.VillaNumber, HttpContext.Session.GetString(StaticDetails.SessionTokenName));
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "VillaNumber created succesfully";
                    return await Task.Run(() => RedirectToAction(nameof(IndexVillaNumber)));
                }
                else
                {
                    if (response.ErrorMessages.Count > 0)
                    {
                        foreach (var errorMessage in response.ErrorMessages)
                        {
                            ModelState.AddModelError("ErrorMessages", errorMessage);
                        }
                    }
                }
            }
            var responseRepopulateList = await _villaService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionTokenName));
            if (responseRepopulateList.IsSuccess && responseRepopulateList.Result != null)
            {
                model.VillaList = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(responseRepopulateList.Result)).Select(x => new SelectListItem()
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });
            }

            TempData["error"] = "Error encountered";
            return await Task.Run(() => View(model));
        }

        [Authorize(Roles = "admin")]

        public async Task<IActionResult> UpdateVillaNumber(int villaNo) 
        {
            VillaNumberUpdateVM villaNumberVM = new();
            var response = await _villaNumberService.GetAsync<APIResponse>(villaNo, HttpContext.Session.GetString(StaticDetails.SessionTokenName));
            if (response != null && response.IsSuccess)
            {
                VillaNumberDTO model = JsonConvert.DeserializeObject<VillaNumberDTO>(Convert.ToString(response.Result));
                villaNumberVM.VillaNumber = _mapper.Map<VillaNumberUpdateDTO>(model);
                var responseVillaList = await _villaService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionTokenName));
                if (responseVillaList.IsSuccess && responseVillaList.Result != null) //lector's if construction assumes there's always gonna be villas. This is better
                {
                    villaNumberVM.VillaList = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(responseVillaList.Result)).Select(x => new SelectListItem()
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    });
                    return await Task.Run(() => View(villaNumberVM));
                }
                return await Task.Run(() => NotFound());
            }
            return await Task.Run(() => NotFound());
        }

        [HttpPost]
        [Authorize(Roles = "admin")]

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateVillaNumber(VillaNumberUpdateVM model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaNumberService.UpdateAsync<APIResponse>(model.VillaNumber, HttpContext.Session.GetString(StaticDetails.SessionTokenName));
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "VillaNumber updated succesfully";
                    return await Task.Run(() => RedirectToAction(nameof(IndexVillaNumber)));
                }
                else
                {
                    if (response.ErrorMessages.Count > 0)
                    {
                        foreach (var errorMessage in response.ErrorMessages)
                        {
                            ModelState.AddModelError("ErrorMessages", errorMessage);
                        }
                    }
                }
            }
            var responseRepopulateList = await _villaService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionTokenName));
            if (responseRepopulateList.IsSuccess && responseRepopulateList.Result != null)
            {
                model.VillaList = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(responseRepopulateList.Result)).Select(x => new SelectListItem()
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });
            }

            TempData["error"] = "Error encountered";
            return await Task.Run(() => View(model));
        }

        [Authorize(Roles = "admin")]

        public async Task<IActionResult> DeleteVillaNumber(int villaNo)
        {
            VillaNumberDeleteVM villaNumberVM = new();
            var response = await _villaNumberService.GetAsync<APIResponse>(villaNo, HttpContext.Session.GetString(StaticDetails.SessionTokenName));
            if (response != null && response.IsSuccess)
            {
                VillaNumberDTO model = JsonConvert.DeserializeObject<VillaNumberDTO>(Convert.ToString(response.Result));
                villaNumberVM.VillaNumber = _mapper.Map<VillaNumberDTO>(model);
                var responseVillaList = await _villaService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionTokenName));
                if (responseVillaList.IsSuccess && responseVillaList.Result != null) //lector's if construction assumes there's always gonna be villas. This is better
                {
                    villaNumberVM.VillaList = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(responseVillaList.Result)).Select(x => new SelectListItem()
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    });
                    return await Task.Run(() => View(villaNumberVM));
                }
                return await Task.Run(() => NotFound());
            }
            return await Task.Run(() => NotFound());
        }
        [HttpPost]
        [Authorize(Roles = "admin")]

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteVillaNumber(VillaNumberDeleteVM model)
        {
            var response = await _villaNumberService.DeleteAsync<APIResponse>(model.VillaNumber.VillaNo, HttpContext.Session.GetString(StaticDetails.SessionTokenName));
            if (response.IsSuccess && response != null)
            {
                TempData["success"] = "VillaNumber deleted succesfully";
                return await Task.Run(() => RedirectToAction(nameof(IndexVillaNumber)));
            }

            TempData["error"] = "Error encountered";
            return await Task.Run(() => View(model));
        }
    }
}

MagicVilla_Web/Views/VillaNumber/CreateVillaNumber.cshtml
@using MagicVilla_Web.Models.ViewModels;
@model VillaNumberCreateVM

<form asp-action="CreateVillaNumber">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Create Villa Number</h1>
        <hr/>

        <div class="row">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="col-2">
                <label asp-for="VillaNumber.VillaNo" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="VillaNumber.VillaNo" class="form-control">
                <span asp-validation-for="VillaNumber.VillaNo" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label asp-for="VillaNumber.VillaId" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="VillaNumber.VillaId" class="form-control" asp-items="@Model.VillaList">
                    <option disabled selected>--Select Villa--</option>
                </select>
                <span asp-validation-for="VillaNumber.VillaId" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label asp-for="VillaNumber.SpecialDetails" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="VillaNumber.SpecialDetails" class="form-control">
                <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger"></span>
            </div>
            <div class="col-5 offset-2">
                <a asp-action="IndexVillaNumber" asp-controller="VillaNumber" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" , value="Create" class="btn btn-success form-control" />
            </div>

        </div>
    </div>
</form>

@section Scripts 
{
    <partial name="_ValidationScriptsPartial" />
}

MagicVilla_Web/Views/VillaNumber/DeleteVillaNumber.cshtml
@using MagicVilla_Web.Models.ViewModels;
@model VillaNumberDeleteVM

<form asp-action="DeleteVillaNumber">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Delete Villa</h1>
        <hr/>
        <input hidden asp-for="@Model.VillaNumber.VillaNo" />
 
        <div class="row">
            <div class="col-2">
                <label asp-for="@Model.VillaNumber.VillaId" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="@Model.VillaNumber.VillaId" disabled class="form-control">
            </div>

            <div class="col-2">
                <label asp-for="@Model.VillaNumber.SpecialDetails" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="@Model.VillaNumber.SpecialDetails" disabled class="form-control">
            </div>
            <div class="col-5 offset-2">
                <a asp-action="IndexVillaNumber" asp-controller="VillaNumber" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-danger form-control" />
            </div>

        </div>
    </div>
</form>

@section Scripts
    {
    <partial name="_ValidationScriptsPartial" />
}

MagicVilla_Web/Views/VillaNumber/IndexVillaNumber.cshtml
@using MagicVilla_Web.Models.DTO;
@model PaginatedListDTO
<br />

<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col">
            <h1 class="text-primary">Villa Number List</h1>
        </div>
        @await Html.PartialAsync("_SearchPartial", Model)
        <div class="col text-end pt-1">
            <a asp-controller="VillaNumber" asp-action="CreateVillaNumber" class="btn btn-outline-primary"> <i class="bi bi-plus-square-fill"></i> <i> Create New Villa Number</i></a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Villa Name
                </th>
                <th>
                    Villa Id
                </th>
                <th>
                    Villa Number
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Items)
            {
                VillaNumberDTO unboxedItem = (VillaNumberDTO)item;
                <tr>
                    <td>@unboxedItem.Villa.Name</td>
                    <td>@unboxedItem.Villa.Id</td>
                    <td>@unboxedItem.VillaNo</td>
                    <td style="border-bottom: none;">
                        <a asp-controller="VillaNumber" asp-action="UpdateVillaNumber" asp-route-villaNo="@unboxedItem.VillaNo" class="btn btn-success"> <i class="bi bi-pencil-square"></i></a>
                        <a asp-controller="VillaNumber" asp-action="DeleteVillaNumber" asp-route-villaNo="@unboxedItem.VillaNo" class="btn btn-danger"> <i class="bi bi-trash-fill"></i></a>
                    </td>

                </tr>
            }
        </tbody>
    </table>
    @await Html.PartialAsync("_PaginationPartial", Model)
</div>

MagicVilla_Web/Views/VillaNumber/UpdateVillaNumber.cshtml
@using MagicVilla_Web.Models.ViewModels;
@model VillaNumberUpdateVM

<form asp-action="UpdateVillaNumber">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Update VillaNumber</h1>
        <hr/>

        <input hidden asp-for="@Model.VillaNumber.VillaNo"/>
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-2">
                <label asp-for="@Model.VillaNumber.SpecialDetails" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="@Model.VillaNumber.SpecialDetails" class="form-control">
                <span asp-validation-for="@Model.VillaNumber.SpecialDetails" class="text-danger"></span>
            </div>

            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="col-2">
                <label asp-for="VillaNumber.VillaId" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 pb-3">
                <select asp-for="VillaNumber.VillaId" class="form-control" asp-items="@Model.VillaList">
                    <option disabled selected>--Select Villa--</option>
                </select>
                <span asp-validation-for="VillaNumber.VillaId" class="text-danger"></span>
            </div>


            <div class="col-5 offset-2">
                <a asp-action="IndexVillaNumber" asp-controller="VillaNumber" class="btn-primary btn form-control ">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Update" class="btn btn-success form-control" />
            </div>

        </div>
    </div>
</form>

@section Scripts 
{
    <partial name="_ValidationScriptsPartial" />
}