MagicVilla_Web/Controllers/AuthController.cs
using AutoMapper;
using MagicVilla_Utility;
using MagicVilla_Web.Models;
using MagicVilla_Web.Models.DTO;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;

namespace MagicVilla_Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IAuthService _authService;

        public AuthController(IMapper mapper, IAuthService authService)
        {
            this._mapper = mapper;
            this._authService = authService;
        }

        public async Task<IActionResult> Login()
        {
            LoginRequestDTO obj = new();
            return await Task.Run(() => View(obj));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginRequestDTO model)
        {
            var response = await _authService.LoginAsync<APIResponse>(model);
            if (response != null && response.IsSuccess)
            {
                LoginResponseDTO loginResponseDTO = JsonConvert.DeserializeObject<LoginResponseDTO>(Convert.ToString(response.Result));

                var handler = new JwtSecurityTokenHandler();
                var jwt = handler.ReadJwtToken(loginResponseDTO.Token);

                var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                identity.AddClaim(new Claim(ClaimTypes.Name, jwt.Claims.FirstOrDefault(x => x.Type == "unique_name").Value)); // claim type is "name" for <= .NET 6 and "unique_name" for >= .NET 7 
                identity.AddClaim(new Claim(ClaimTypes.Role, jwt.Claims.FirstOrDefault(x=>x.Type=="role").Value)); // JWT specific claim type magic string
                var principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(principal); 

                HttpContext.Session.SetString(StaticDetails.SessionTokenName, loginResponseDTO.Token);

                TempData["success"] = "Login successful";
                return await Task.Run(() => RedirectToAction("Index", "Home"));
            }

            ModelState.AddModelError("CustomError", response.ErrorMessages.FirstOrDefault());
            TempData["error"] = "Error encountered";
            return await Task.Run(() => View(model));
        }

        public async Task<IActionResult> Register()
        {
            RegistrationRequestDTO obj = new();
            return await Task.Run(() => View(obj));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegistrationRequestDTO model)
        {
            APIResponse response = await _authService.RegisterAsync<APIResponse>(model);
            if (response != null && response.IsSuccess)
            {
                return await Task.Run(() => RedirectToAction("Login"));
            }

            ModelState.AddModelError("CustomError", response.ErrorMessages.FirstOrDefault());
            TempData["error"] = "Error encountered";
            return await Task.Run(() => View(model));
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            HttpContext.Session.Clear();
            //HttpContext.Session.SetString(StaticDetails.SessionToken, string.Empty); //used by author, otherwise it is null
            return await Task.Run(() => RedirectToAction("Index","Home"));
        }

        public async Task<IActionResult> AccessDenied()
        {
            return await Task.Run(() => View());
        }
    }
}

MagicVilla_Web/Controllers/VillaController.cs
using AutoMapper;
using MagicVilla_Utility;
using MagicVilla_Web.Models;
using MagicVilla_Web.Models.DTO;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Data;

namespace MagicVilla_Web.Controllers
{
    public class VillaController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IVillaService _villaService;

        public VillaController(IMapper mapper, IVillaService villaService)
        {
            this._mapper = mapper;
            this._villaService = villaService;
        }
        public async Task<IActionResult> IndexVilla(int pageSize = 5, int pageNumber = 1, string searchString = "")
        {
            List<VillaDTO> list = new List<VillaDTO>();
            var response = await _villaService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(StaticDetails.SessionTokenName), pageSize, pageNumber, searchString);

            var paginationHeaderValue = response.Headers.FirstOrDefault(x => x.Key == "X-Pagination").Value[0];

            var pagination = JsonConvert.DeserializeObject<Pagination>(paginationHeaderValue);

            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result));
            }
            var paginatedResults = new PaginatedListDTO(list, pagination.TotalResultsCount, pageNumber, pageSize, searchString);

            return await Task.Run(() => View(paginatedResults));
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateVilla()
        {
            return await Task.Run(() => View());
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateVilla(VillaCreateDTO model)
        {

            if (ModelState.IsValid)
            {
                var response = await _villaService.CreateAsync<APIResponse>(model, HttpContext.Session.GetString(StaticDetails.SessionTokenName));
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Villa created succesfully";
                    return await Task.Run(() => RedirectToAction(nameof(IndexVilla)));
                }
            }

            TempData["error"] = "Error encountered";
            return await Task.Run(() => View(model));
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateVilla(int villaId)
        {
            var user = HttpContext.User.Claims;// TO DO DELETE
            var response = await _villaService.GetAsync<APIResponse>(villaId, HttpContext.Session.GetString(StaticDetails.SessionTokenName));
            if (response != null && response.IsSuccess)
            {
                VillaDTO model = JsonConvert.DeserializeObject<VillaDTO>(Convert.ToString(response.Result));
                return await Task.Run(() => View(_mapper.Map<VillaUpdateDTO>(model)));
            }
            return await Task.Run(() => NotFound());
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateVilla(VillaUpdateDTO model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaService.UpdateAsync<APIResponse>(model, HttpContext.Session.GetString(StaticDetails.SessionTokenName));
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Villa updated succesfully";
                    return await Task.Run(() => RedirectToAction(nameof(IndexVilla)));
                }
            }

            TempData["error"] = "Error encountered";
            return await Task.Run(() => View(model));
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteVilla(int villaId)
        {
            var response = await _villaService.GetAsync<APIResponse>(villaId, HttpContext.Session.GetString(StaticDetails.SessionTokenName));
            if (response != null && response.IsSuccess)
            {
                VillaDTO model = JsonConvert.DeserializeObject<VillaDTO>(Convert.ToString(response.Result));
                return await Task.Run(() => View(model));
            }
            return await Task.Run(() => NotFound());
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteVilla(VillaDTO model)
        {
            var response = await _villaService.DeleteAsync<APIResponse>(model.Id, HttpContext.Session.GetString(StaticDetails.SessionTokenName));
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Villa deleted succesfully";
                return await Task.Run(() => RedirectToAction(nameof(IndexVilla)));
            }

            TempData["error"] = "Error encountered";
            return await Task.Run(() => View(model));
        }
    }
}

MagicVilla_Web/Views/Shared/_Layout.cshtml
@using MagicVilla_Utility;
@inject IHttpContextAccessor httpAcc;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MagicVilla_Web</title>
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MagicVilla_Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <partial name="_Notification" />
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Villa" asp-action="IndexVilla">Villa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VillaNumber" asp-action="IndexVillaNumber">Villa Number</a>
                        </li>
                        @if (httpAcc.HttpContext.Session.GetString(StaticDetails.SessionTokenName) != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container text-center">
            &copy; 2023 - MagicVilla_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MagicVilla_Web/Views/Shared/_Notification.cshtml
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
@if (TempData["success"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'success',
            title: '@TempData["success"]',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true
        })
    </script>
}
@if (TempData["failure"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'failure',
            title: '@TempData["error"]',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true
        })
    </script>
}

MagicVilla_Web/Views/Shared/_PaginationPartial.cshtml
@using MagicVilla_Web.Models.DTO;
@using System.Text.RegularExpressions;

@model PaginatedListDTO;

@{
    string mainViewName = ViewContext.ActionDescriptor.DisplayName;
    string pattern = @"(?<Controller>\w+)Controller\.(?<Action>\w+)\s*\(.+";
    Match match = Regex.Match(mainViewName, pattern);
    string controllerName = match.Groups["Controller"].Value;
    string actionName = match.Groups["Action"].Value;
    var a = 5;
}

<div class="row justify-content-between align-items-center">
    <div class="col-auto">
        @if (Model.HasPreviousPage)
        {
            <a asp-action=@actionName asp-controller=@controllerName asp-route-pageNumber="1" class="btn btn-default">
                First Page
            </a>
        }
    </div>

    <div class="col-auto">
        @if (Model.HasPreviousPage)
        {
            <a asp-action=@actionName asp-controller=@controllerName asp-route-pageNumber="@(Model.PageNumber-1)" class="btn btn-default">
                Previous Page
            </a>
        }
    </div>
    <div class="col-auto">
        @if (Model.HasNextPage)
        {
            <a asp-action=@actionName asp-controller=@controllerName asp-route-pageNumber="@(Model.PageNumber+1)" class="btn btn-default">
                Next Page
            </a>
        }
    </div>
    <div class="col-auto">
        @if (Model.HasNextPage)
        {
            <a asp-action=@actionName asp-controller=@controllerName asp-route-pageNumber="@(Model.TotalPages)" class="btn btn-default">
                Last Page
            </a>
        }
    </div>
</div>

<div class="row justify-content-center mt-3">
    <div class="col-auto">
        <div class="d-flex align-items-center">
            <span class="mr-3">Results per page:</span>&nbsp;&nbsp;
            <form asp-action=@actionName asp-controller=@controllerName>
                <select name="pageSize" asp-for="@Model.PageSize" onchange="javascript:this.form.submit()" class="form-select" style="width: 6em;">
                    <option disabled>Choose...</option>
                    <option value="5">5</option>
                    <option value="10">10</option>
                    <option value="20">20</option>
                    <option value="50">50</option>
                </select>
            </form>
        </div>
    </div>
    <div class="col-auto d-flex align-items-center">
        @if (Model.Items.Any())
        {
            <div class="align-self-center">
                Displaying results @((Model.PageNumber - 1) * Model.PageSize + 1) to
                @((Model.PageNumber - 1) * Model.PageSize + Model.Items.Count()) of @Model.EntriesCount
            </div>
        }
        else
        {
            <span>No entries to display</span>
        }
    </div>
</div>

MagicVilla_Web/Views/Shared/_SearchPartial.cshtml
@using MagicVilla_Web.Models.DTO;
@using System.Text.RegularExpressions;

@model PaginatedListDTO;

@{
    string mainViewName = ViewContext.ActionDescriptor.DisplayName;
    string pattern = @"(?<Controller>\w+)Controller\.(?<Action>\w+)\s*\(.+";
    Match match = Regex.Match(mainViewName, pattern);
    string controllerName = match.Groups["Controller"].Value;
    string actionName = match.Groups["Action"].Value;
}

<div class="col">
    <form asp-controller=@controllerName asp-action=@actionName asp-route-search="" class="form-inline">
        <div class="input-group">
            <input type="text" name="searchString" class="form-control" placeholder="Search..." value="@Model.SearchString" />
            <button type="submit" class="btn btn-outline-secondary">Search</button>
        </div>
    </form>
</div>